import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import { PrismaClient } from "@prisma/client";
import statsRouter from "./routes/stats";
import invoicesRouter from "./routes/invoices";
import vendorsRouter from "./routes/vendors";
import categoryRouter from "./routes/category";
import cashRouter from "./routes/cash";
import chatRouter from "./routes/chat";
dotenv.config();
const app = express();
app.use(cors({ origin: process.env.NEXT_PUBLIC_APP_URL || "*" }));
app.use(express.json());
const prisma = new PrismaClient();
app.get("/health", (req, res) => res.json({status: "ok"}));
app.use("/stats", statsRouter(prisma));
app.use("/invoices", invoicesRouter(prisma));
app.use("/vendors/top10", vendorsRouter(prisma));
app.use("/category-spend", categoryRouter(prisma));
app.use("/cash-outflow", cashRouter(prisma));
app.use("/chat-with-data", chatRouter(process.env.VANNA_API_BASE_URL, process.env.VANNA_API_KEY, prisma));
const port = Number(process.env.PORT || 4000);
app.listen(port, () => console.log(`API listening on ${port}`));